# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - run: npm ci
      - run: npm ci --workspace=@axync/random
      - run: npm run build --workspace=@axync/random
      - run: npm ci --workspace=@axync/extract-html-main-content
      - run: npm run build --workspace=@axync/extract-html-main-content
      - run: npm ci --workspace=@axync/extract-json
      - run: npm run build --workspace=@axync/extract-json
      - run: npm ci --workspace=@axync/memorize
      - run: npm run build --workspace=@axync/memorize
      - run: npm ci --workspace=@axync/pubsub
      - run: npm run build --workspace=@axync/pubsub
      - run: npm run test --workspaces

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - run: npm ci
      - run: npm ci --workspace=@axync/random
      - run: npm run build --workspace=@axync/random
      - run: npm ci --workspace=@axync/extract-html-main-content
      - run: npm run build --workspace=@axync/extract-html-main-content
      - run: npm ci --workspace=@axync/extract-json
      - run: npm run build --workspace=@axync/extract-json
      - run: npm ci --workspace=@axync/memorize
      - run: npm run build --workspace=@axync/memorize
      - run: npm ci --workspace=@axync/pubsub
      - run: npm run build --workspace=@axync/pubsub
      - run: npm run test --workspaces

      - name: Publish
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages
          # and calls changeset publish
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}